USE [master]
GO

/****** Object:  Database [TesteTI]    Script Date: 22/07/2021 23:46:00 ******/
CREATE DATABASE [TesteTI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TesteTI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TesteTI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TesteTI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TesteTI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TesteTI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TesteTI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TesteTI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TesteTI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TesteTI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TesteTI] SET ARITHABORT OFF 
GO

ALTER DATABASE [TesteTI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TesteTI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TesteTI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TesteTI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TesteTI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TesteTI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TesteTI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TesteTI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TesteTI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TesteTI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TesteTI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TesteTI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TesteTI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TesteTI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TesteTI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TesteTI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TesteTI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TesteTI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TesteTI] SET  MULTI_USER 
GO

ALTER DATABASE [TesteTI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TesteTI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TesteTI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TesteTI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TesteTI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TesteTI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TesteTI] SET  READ_WRITE 
GO


